# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

flutter_application_path = '../../esewa_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'esewa_ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

  # Pods for esewa_ios_app

  target 'esewa_ios_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'esewa_ios_appUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end

